name: 'Build & Deploy'

on:
  push:
    branches:
    - develop
  pull_request:

env: 
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  WORKER_SA: ${{ secrets.WORKER_SA }}

jobs:
  build-deploy:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.IDENTITY }}
    
    - name: impersonate
      run: export GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud auth print-access-token --impersonate-service-account=$WORKER_SA)
        
    - name: Build
      run: |
        docker build -t "gcr.io/$PROJECT_ID:latest" .

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_KEY }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      run: terraform apply -auto-approve
